exports.addNewProject = (
  projectName,
  projectDescription,
  size,
  width,
  length,
  height,
  livingRoomsNumber,
  bathRoomsNumber,
  carGarageNumber,
  floorsNumber,
  bedRoomsNumber,
  kitchenDescription,
  roomsDescription,
  garageDescription,
  gardenDescription,
  gardenChart,
  interiorDecorationChart,
  HealthChart,
  executiveCahrt,
  buildingChart,
  quantityChart,
  electricityChart,
  conditioningChart,
  price,
  urlArray
) => ({
  text: `INSERT INTO projects(name, description, size, width, length, height,
            livingrooms_number, bathrooms_number,
            car_garage_number,
            floors_number,
            bedrooms_number,
            kitchen_description ,
            rooms_description ,
            garage_description ,
            garden_description, garden_chart,
            interior_decoration_chart,
            health_chart,
            executive_cahrt,
            building_chart,
            quantity_chart,
            electricity_chart,
            conditioning_chart, 
            price,
            images_url,
            sold ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)`,
  values: [
    projectName,
    projectDescription,
    size,
    width,
    length,
    height,
    livingRoomsNumber,
    bathRoomsNumber,
    carGarageNumber,
    floorsNumber,
    bedRoomsNumber,
    kitchenDescription,
    roomsDescription,
    garageDescription,
    gardenDescription,
    gardenChart,
    interiorDecorationChart,
    HealthChart,
    executiveCahrt,
    buildingChart,
    quantityChart,
    electricityChart,
    conditioningChart,
    price,
    urlArray,
    false,
  ]
});

exports.getAllProjects = () => ({
  text: 'select * FROM projects WHERE sold = $1',
  values: [false]
})

