exports.addNewProject = (
  projectName,
  projectDescription,
  size,
  width,
  length,
  height,
  livingRoomsSize,
  bathRoomsSize,
  carGarageSize,
  floorsSize,
  bedRoomsSize,
  kitchenDescription,
  roomsDescription,
  garageDescription,
  gardenDescription,
  gardenChart,
  interiorDecorationChart,
  HealthChart,
  executiveCahrt,
  buildingChart,
  quantityChart,
  electricityChart,
  conditioningChart,
  price,
  urlArray
) => ({
  text: `INSERT INTO projects(name, description, size, width, length, height, livingrooms_size, bathrooms_size,
            car_garage_size,
            floors_size,
            bedrooms_size,
            kitchen_description ,
            rooms_description ,
            garage_description ,
            garden_description, garden_chart,
            interior_decoration_chart,
            health_chart,
            executive_cahrt,
            building_chart,
            quantity_chart,
            electricity_chart,
            conditioning_chart, 
            price,
            images_url ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25)`,
  values: [
    projectName,
    projectDescription,
    size,
    width,
    length,
    height,
    livingRoomsSize,
    bathRoomsSize,
    carGarageSize,
    floorsSize,
    bedRoomsSize,
    kitchenDescription,
    roomsDescription,
    garageDescription,
    gardenDescription,
    gardenChart,
    interiorDecorationChart,
    HealthChart,
    executiveCahrt,
    buildingChart,
    quantityChart,
    electricityChart,
    conditioningChart,
    price,
    urlArray
  ]
});


