exports.addNewProject = (
  projectName,
  projectDescription,
  size,
  width,
  length,
  height,
  livingRoomsNumber,
  bathRoomsNumber,
  carGarageNumber,
  floorsNumber,
  bedRoomsNumber,
  kitchenDescription,
  roomsDescription,
  garageDescription,
  gardenDescription,
  charts,
  price,
  urlArray,
  projectMainImage,
  filesUrlArray
) => ({
  text: `INSERT INTO projects(name, description, size, width, length, height,
            livingrooms_number, bathrooms_number,
            car_garage_number,
            floors_number,
            bedrooms_number,
            kitchen_description ,
            rooms_description ,
            garage_description ,
            garden_description, 
            charts,
            price,
            images_urls,
            sold,
            project_wallpaper,
            files_urls) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16 , $17, $18, $19, $20, $21)`,
  values: [
    projectName,
    projectDescription,
    size,
    width,
    length,
    height,
    livingRoomsNumber,
    bathRoomsNumber,
    carGarageNumber,
    floorsNumber,
    bedRoomsNumber,
    kitchenDescription,
    roomsDescription,
    garageDescription,
    gardenDescription,
    charts,
    price,
    urlArray,
    false,
    projectMainImage,
    filesUrlArray
  ]
});

exports.getAllProjects = () => ({
  text: 'select * FROM projects WHERE sold = $1',
  values: [false]
})

